#!/bin/bash
VERSION_x11docker2deb=0.3
VERSION_x11docker=`./x11docker --version`
echo "Version of x11docker2deb : $VERSION_x11docker2deb"
echo "Version of x11docker : $VERSION_x11docker"
mkdir -p x11docker-deb/usr/bin
mkdir -p x11docker-deb/usr/share/man/man1
cp ./x11docker ./x11docker-deb/usr/bin
mkdir -p x11docker-deb/DEBIAN
cat > ./x11docker-deb/DEBIAN/control << EOF
Package: x11docker
Version: $VERSION_x11docker
Architecture: all
Priority: optional
Depends: bash
Installed-Size: 450
Sections: x11
Recommends: nxagent, xserver-xephyr, xdotool, xauth, xinit, xclip, xutils, xserver-xorg, docker.io | podman
Suggests: weston, xwayland
Maintainer: Jy Deng <djy99811899@pku.edu.cn>
Description: A tool to run GUI applications and desktops in Linux containers with backends like podman or docker. X11docker helps to avoid X security leaks and enhance container security. Software can be installed in a deployable image with a rudimentary Linux system inside. This can help to run or deploy software that is difficult to install on several systems due to dependency issues. It is possible to run outdated versions or latest development versions side by side. Files to work on can be shared between host and container.
EOF
help2man ./x11docker --no-discard-stderr > ./man
gzip --keep ./man
mv ./man.gz ./x11docker-deb/usr/share/man/man1/x11docker.1.gz
dpkg -b ./x11docker-deb x11docker-$VERSION_x11docker.deb
